name: Build and Deploy
on:
  push:
    branches:
    - master

env:
  NODE_VERSION: '12.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@master
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install
      - run: npm run build --if-present
      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.2
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: gdg-vilnius-aura
